spring:
  application:
    name: delivery-API-Service
  boot:
    admin:
      client:
        url: http://localhost:1111/
server:
  port: 9093
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#for Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'